[package]
name = "collatz"
version = "0.1.0"
authors = ["Vanessa McHale <vamchale@gmail.com>"]
exclude = [ ".gitignore" ]

[dependencies]
num-bigint = "0.1"
num-traits = "0.1"
rust-gmp = "0.5.0"

[profile.release]
lto = true
